getOtherKey relation was moved to Pivot
Illuminate\Database\Eloquent\Relations\Pivot

This affected an issue when adding anything (admin, role,  inside the panel application:

BadMethodCallException: Call to undefined method Illuminate\Database\Query\Builder::getOtherKey()